### ISSUE TITLE
Wrong classpath in getting started docs

### ISSUE THREAD

**Issue by brainbytes42** [johnrengelman/shadow#811] opened 2022-12-13 10:16 UTC
I need to include the (great!) shadow-plugin in a conventions-plugin, so I needed to rely on the 'old' apply-plugin-style.

According to the [Getting-Started-Docs](https://imperceptiblethoughts.com/shadow/getting-started/), the dependencies-classpath is `classpath 'gradle.plugin.com.github.jengelman.gradle.plugins:shadow:7.1.2'`, but then the Plugin isn't found. (Even without convention plugin but just in this short example from the docs.)

Referring to the Path stated in #807, I tried `classpath 'gradle.plugin.com.github.johnrengelman:shadow:7.1.2'`, which works for the example. (And this is also the implementation-dependency, I need to add to my convention-plugin's buildscript-dependencies; for the plugin itself, i's the id used for apply plugin in the example.)

Please update the Documentation, this issue has cost me some time and nerves... ;-)

(Additional question for gradle-user but not expert: Where could I have found the correct classpath? I searched shadow's buildscript and settings, but didn't get the path right until I found the cited issue...)

**Comment by ferozed** [comment] 2022-12-20 18:57
+1 to this. Please fix the docs.

**Comment by iGoodie** [comment] 2022-12-31 18:52
Yea, this one got me confused too. Thanks for putting `classpath 'gradle.plugin.com.github.johnrengelman:shadow:7.1.2'` there btw

**Comment by 3flex** [comment] 2023-01-02 11:45
Looks like a duplicate of #802

**Comment by johnrengelman** [comment] 2023-03-21 03:45
I've updated the docs to reflect the correct package name and put a note indicating that users should check the official gradle plugin portal for the correct package at each version.

hopefully, this won't change again in the future. It appears that Gradle has stabilized on a package name that aligns with the plugin id.

**Closed by johnrengelman** 2023-03-21 03:45 UTC
