### ISSUE TITLE
Wrong coordinate on the project website?

### ISSUE THREAD

**Issue by oldergod** [johnrengelman/shadow#841] opened 2023-03-13 10:44 UTC
The getting started page https://imperceptiblethoughts.com/shadow/getting-started/#default-java-groovy-tasks

gives those coordinates. I believe the prefix `gradle.plugin.` is wrong and should be removed?

```
buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath 'gradle.plugin.com.github.johnrengelman:shadow:8.1.0'
    }
}
```

**Comment by Goooler** [comment] 2023-03-13 14:35
Duplicate of #827

**Closed** 2023-03-20 19:27 UTC
