### ISSUE TITLE
Gradle mainClassName is deprecated will be removed in v7.x

### ISSUE THREAD

**Issue by phreed** [johnrengelman/shadow#645] opened 2021-03-09 16:32 UTC
### Shadow Version
v 6.1.0

### Gradle Version
v 6.8.3

### Expected Behavior
Accept the Gradle recommended main-class-name. 

```
val mainClassPath = "the main class package/name"
application {
    mainClass.set(mainClassPath)
}
```

### Actual Behavior

The deprecated `mainClassName` must be specified.
The warning can be suppressed but must be corrected for Gradle v7.x
```
application {
    mainClass.set(mainClassPath)
    @Suppress("DEPRECATION")
    mainClassName = mainClassPath
}
```

**Comment by efenderbosch** [comment] 2021-03-11 14:23
dupe of #631 #609 #612

**Closed** 2021-04-01 17:00 UTC
