### ISSUE TITLE
Shadow doesn't recognise application's new mainClass property

### ISSUE THREAD

**Issue by BomBardyGamer** [johnrengelman/shadow#662] opened 2021-04-10 22:32 UTC
Please check the [User Guide](http://imperceptiblethoughts.com/shadow) before submitting "how do I do 'x'?" questions!

### Shadow Version
6.1.0

### Gradle Version
7.0

### Expected Behavior
`shadowJar` recognises the new `mainClass` property (replaces the old `mainClassName` string field) and uses it appropriately

### Actual Behavior
`shadowJar` errors out because it can't find the value for the `mainClassName` property

### Gradle Build Script(s)
https://pastebin.com/TJWFV78p (you can see if I comment out the old property and set the new property, it doesn't work)

### Content of Shadow JAR (`jar tf <jar file>` - post link to GIST if too long)
N/A

**Comment by boris-petrov** [comment] 2021-04-15 08:07
@BomBardyGamer - this is a duplicate of #645, #631, #609, #612.

**Closed** 2021-04-15 15:18 UTC
