### ISSUE TITLE
minimizeJar

### ISSUE THREAD

**Issue by Petikoch** [johnrengelman/shadow#115] opened 2014-12-07 19:15 UTC
Hi @johnrengelman ,

I was wondering if shadow has also a _minimizeJar_ like feature like the maven-shade-plugin:  http://maven.apache.org/plugins/maven-shade-plugin/examples/includes-excludes.html

Best regards,
Peti

**Comment by johnrengelman** [comment] 2015-09-17 03:19
Gonna reopen this to track possible future enhancements.

**Comment by Petikoch** [comment] 2015-09-17 06:31
:+1:

**Comment by sporkthrower** [comment] 2015-09-18 20:03
I have a somewhat related question, which may be feasible with current exclude capabilities, and I just don't know how to accomplish it.

We know which packages of guava we are using and want to include and shade those with our jar (ie:  base, collect, primitives) .  In the interest of keeping the jar small we would like to globally exclude the other com.google.common packages entirely.

I can exclude them from the shading easily enough 
```
relocate("com.", "mypackage.com." ) {
  exclude "com.google.common.eventbus**"
  exclude "com.google.common.hash**"
  exclude "com.google.common.io.**"
  exclude "com.google.common.math.**"
  exclude "com.google.common.net.**"
  exclude "com.google.common.reflect.**"
  exclude "com.google.common.util.**"
}
```
However, they are then left unshaded in the jar, and I'm having trouble figuring out how to globally exclude them.    

It looks to me like the dependency exclusion is all or nothing of a maven group:name so I can't do a partial guava exclusion ie ```exclude(dependency('com.google.guava:guava????'))``` .  

So far I haven't been able to get a file exclusion regex pattern to match and exclude them.  Do you have any advice for how we might be able to accomplish this with the shadowJar?   We used to used fatjar plugin and an ant jarjar task to do this, but the old way won't work since a gradle upgrade.

**Comment by janschaefer** [comment] 2016-11-09 08:20
Seems to be a duplicate of #198

**Comment by johnrengelman** [comment] 2016-11-09 17:04
Yup. Closing this in favor of tracking enhancements on https://github.com/johnrengelman/shadow/issues/198

**Closed by johnrengelman** 2016-11-09 17:04 UTC
Labels: enhancement
