### ISSUE TITLE
When adding a jar inside a jar, instead of nesting it, the tool explodes it within the outer jar.

### ISSUE THREAD

**Issue by Lanchon** [johnrengelman/shadow#151] opened 2015-07-17 09:29 UTC
```
shadowJar {
    archiveName = 'fat.jar'
    from 'my-dir'
}
```

where `my-dir/contains-a.jar` causes`'contains-a.jar` to be exploded within `fat.jar` instead of being nested inside it.

workaround -> double-nest the inner jar:

```
task workaround(type: Jar) {
    baseName = 'workaround'
    from 'my-dir'
}

shadowJar {
    archiveName = 'fat.jar'
    from workaround
}
```

**Comment by johnrengelman** [comment] 2015-07-17 17:21
Duplicate of https://github.com/johnrengelman/shadow/issues/136

**Closed by johnrengelman** 2015-07-17 17:21 UTC
