### ISSUE TITLE
any way to control compression level?

### ISSUE THREAD

**Issue by glebsts** [johnrengelman/shadow#226] opened 2016-07-06 08:34 UTC
Hello,
Shadow 1.2.3, Gradle 2.10
I see ZipOutputStream.DEFLATED in default Gradle111DefaultZipCompressor. My goal is to create no-compression jar (ZipOutputStream.STORED). 
I.e. for gradle Zip task you can set entryCompression, I need same for shadowJar task.
It was written that shadowJar inherits from Jar, and Jar according to docs has entryCompression property that could be set to ZipEntryCompression.*, but STORED is kinda speficic, as it gives me

``` :shadowJarex
org.gradle.api.GradleException: Could not add META-INF to ZIP xxx-all.jar
...
at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction$StreamAction.visitDir(ShadowCopyAction.groovy:309)
...
Caused by: java.util.zip.ZipException: uncompressed size is required for STORED method when not writing to a file
        at org.apache.tools.zip.ZipOutputStream.validateSizeInformation(ZipOutputStream.java:699)
```

Any way to control it in gradle file?
Thank you.

**Comment by timyitong** [comment] 2016-09-24 00:30
+1 one for this. I ran into a situation where uncompressed jar is preferred so that `rsync` could do a better job transferring jars and `fatJar` doesn't work because shading/relocation is also important.

**Comment by johnrengelman** [comment] 2016-11-19 16:16
Duplicate of https://github.com/johnrengelman/shadow/issues/203

**Closed by johnrengelman** 2016-11-19 16:16 UTC
Labels: bug, duplicate
