### ISSUE TITLE
Add Support For Making It Work With Gradle Maven Plugin

### ISSUE THREAD

**Issue by ankurpathak** [johnrengelman/shadow#429] opened 2018-11-20 03:07 UTC
The instant I add this Plugin To My Java Project It starts Breaking The Functionality of Gradle Maven
Plugin. I can't understand the exact issue as I am new to Gradle. On Adding this plugin When I run
gradle install Task of Gradle Maven Plugin, it fails with following stack trace:
> Task :install FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':install'.
> Could not publish configuration 'archives'
   > A POM cannot have multiple artifacts with the same type and classifier. Already have MavenArtifact gradle-test:zip:zip:null, trying to add MavenArtifact gradle-test:zip:zip:null.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
10 actionable tasks: 1 executed, 9 up-to-date

The instant I remove this plugin, gradle install of Gradle Maven Plugin work fine. I think it had something
to do with two artifacts it creating in build/libs namely xxx.jar and xxx-all.jar.

The similar is the functionality of Gradle Spring Boot Plugin, which also creates new artifact by modifying
orignal artifact.But id doesn't break any existing plugin Gradle Maven Plugin.

Thus behaviour of Shadow plugin should be similar to Gradle Spring Boot Plugin, and it should not
break Gradle Maven Plugin.

**Comment by johnrengelman** [comment] 2018-11-21 21:48
Duplicate of https://github.com/johnrengelman/shadow/issues/347.
Workaround that issue.

**Closed by johnrengelman** 2018-11-21 21:48 UTC
