### ISSUE TITLE
Broken on Gradle 2.5 and 2.6

### ISSUE THREAD

**Issue by kensipe** [johnrengelman/shadow#154] opened 2015-08-12 14:33 UTC
A build with shadow was working gradle 2.4.   an upgrade to 2.5 or 2.6 results in the following:

Caused by: java.lang.NoClassDefFoundError: org.gradle.mvn3.org.codehaus.plexus.util.IOUtil

**Comment by centic9** [comment] 2015-08-12 20:25
Seemingly a duplicate of #147 and #148

**Comment by johnrengelman** [comment] 2015-08-13 01:40
@kensipe are you using the latest `1.2.2` release?

**Closed** 2015-09-17 03:30 UTC
Labels: duplicate
