### ISSUE TITLE
ZipException: invalid literal/lengths set

### ISSUE THREAD

**Issue by Favorlock** [johnrengelman/shadow#208] opened 2016-04-22 19:00 UTC
Here is the exception I'm getting: http://pastebin.com/yfUJzA8S

A temporary solution is renaming the extension from .zip to .zipx. If a file is in the resource folder you shouldn't be attempting to explode it whatsoever. It's in the resource folder for a reason.

**Comment by johnrengelman** [comment] 2016-04-22 19:42
Duplicate of https://github.com/johnrengelman/shadow/issues/196

**Closed by johnrengelman** 2016-04-22 19:42 UTC
