### ISSUE TITLE
plugins.gradle.org/m2/gradle/plugin/com/github/johnrengelman/shadow is missing version 8.1.0

### ISSUE THREAD

**Issue by JT122406** [johnrengelman/shadow#840] opened 2023-03-08 04:43 UTC
Version 8.1.0 is missing from:
https://plugins.gradle.org/m2/gradle/plugin/com/github/johnrengelman/shadow/8.1.0

**Comment by Goooler** [comment] 2023-03-08 12:42
Duplicate of #827

**Closed** 2023-03-20 19:27 UTC
