### ISSUE TITLE
Zip and tar files created in addition to shadow jar file

### ISSUE THREAD

**Issue by jeffbeard** [johnrengelman/shadow#153] opened 2015-07-28 13:17 UTC
The combo of the application and shadow plugins apparently triggers the creation of both a zip and tar file. These unnecessary files are also uploaded to our Maven repository which means that we're creating a lot of unused data.

I can't figure out if there's configuration to disable the creation of the zip and tar files but it would be nice if there was.

**Comment by johnrengelman** [comment] 2015-11-28 05:23
what is the task you are running from the Gradle command line?

**Comment by kurtseebauer** [comment] 2015-12-05 14:47
it's the application-plugin that adds the zip and tar distribution targets when you run the task bootRepackage.

**Comment by jeffbeard** [comment] 2015-12-18 13:18
@kurtseebauer 's answer is probably more technically accurate. We wire the 'shadowJar' task into the 'jar' task then we just run './gradlew build'

**Comment by johnrengelman** [comment] 2016-06-24 22:22
Closing as this isn't an issue with Shadow

**Closed by johnrengelman** 2016-06-24 22:22 UTC

**Comment by patrickherrera** [comment] 2019-02-26 06:14
For anyone else coming across this, you can try something like this to disable these tasks:
`tasks.whenTaskAdded { task ->
    if (Arrays.asList("shadowDistZip", "shadowDistTar", "distZip", "distTar").contains(task.name)) {
        task.enabled = false
    }
}`

Not ideal, but it works so far.

**Comment by elmagnoon** [comment] 2023-03-09 09:04
Even though the issue is closed, the previous solutions didn't work for me. Currently using Gradle 8.0.1. The below worked.

```
tasks.distZip.setEnabled(false)
tasks.distTar.setEnabled(false)
tasks.shadowDistZip.setEnabled(false)
tasks.shadowDistTar.setEnabled(false)
```
