### ISSUE TITLE
Missing spring-boot when using spring-boot-gradle-plugin

### ISSUE THREAD

**Issue by trunganh39** [johnrengelman/shadow#296] opened 2017-05-04 15:00 UTC
### Shadow Version
1.2.4

### Gradle Version
2.14.1

### Expected Behavior
Org.springframework.boot is included as a dependency in the project. I am expecting that when using shadowJar task, it should be expanded in the out jar as well.

### Actual Behavior
However, it is not. It is not included in the output jar and nowhere is referencing it even in manifest file.

### Gradle Build Script(s)

[build.gradle.zip](https://github.com/johnrengelman/shadow/files/976546/build.gradle.zip)

### Content of Shadow JAR (`jar tf <jar file>` - post link to GIST if too long)

[output.txt](https://github.com/johnrengelman/shadow/files/976568/output.txt)

**Comment by johnrengelman** [comment] 2017-05-12 04:20
the boot framework has it's own gradle plugin and method for packaging ditributable jar files. I dont' think I would combine shadow and the boot plugin in the same project. They will collide.

**Comment by johnrengelman** [comment] 2017-05-12 04:22
Closing as duplicate of https://github.com/johnrengelman/shadow/issues/199

**Closed by johnrengelman** 2017-05-12 04:22 UTC
