### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by DouglasBrunner** [johnrengelman/shadow#189] opened 2016-03-14 16:21 UTC
I'm trying to track down the source of a NoClassDefFoundError. When I run my code in IntelliJ everything works as expected but when the same code is assembled by shadowJar and run I'm getting a NoClassDefFoundError, caused by a ClassNotFoundException. This leads me to believe something isn't being packaged correctly.

The problem is caused by calling [Either.right()](http://www.javaslang.io/javadoc/snapshot/javaslang/control/Either.html#right--) of the JavaSlang library, [code here](https://github.com/javaslang/javaslang/blob/master/javaslang/src/main/java/javaslang/control/Either.java).

Here is the smallest example which reproduces the error.

*eitherProblem.gradle*
```
plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '1.2.3'
}

group 'eitherProblem'
version '1.0-SNAPSHOT'

apply plugin: 'application'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    compile 'com.javaslang:javaslang:2.0.0-RC4'
}

mainClassName = 'Main'

jar {
    manifest {
        attributes 'Main-Class': mainClassName
    }
}
```

*Main.java*
```
import javaslang.control.Either;

public class Main {

    public static void main(String[] args) {

        System.out.println("Before");
        Either.right("right content");
        System.out.println("After");

    }
}
```

*intellij output*
```
Before
After 
```

*console (java -jar) output*
```
Before
Exception in thread "main" java.lang.NoClassDefFoundError: javaslang/?
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at Main.main(Main.java:8)
Caused by: java.lang.ClassNotFoundException: javaslang.?
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 25 more
```

**Comment by johnrengelman** [comment] 2016-03-14 18:48
Which jar are you trying to run? The Shadow jar or just a the normal Jar?

**Comment by DouglasBrunner** [comment] 2016-03-14 21:54
Running shadowJar produces one jar file in ``build/libs``. The jar is named [app name]-[version]-all.jar

If I open the jar file and look inside it contains the JavaSlang classes.

**Comment by johnrengelman** [comment] 2016-03-15 16:48
Can you post an example project that exhibits the problem?

**Comment by DouglasBrunner** [comment] 2016-03-15 23:14
Of course. I have a project on BitBucket: https://bitbucket.org/DouglasBrunner/wordsmith/

I've read that the error can be thrown by a [static initializer](http://stackoverflow.com/a/6352584/1306502), but since the program works as expected when run via IntelliJ I haven't pursed it much further. It still may be relevant so I figured I should post the link.

**Comment by johnrengelman** [comment] 2016-06-24 22:17
This is duplicate of https://github.com/johnrengelman/shadow/issues/223 (although this was the first issue).
Refer to #223 for updates.

**Closed by johnrengelman** 2016-06-24 22:17 UTC
Labels: bug
