### ISSUE TITLE
Can't build a standalone *library* (no property 'mainClassName')

### ISSUE THREAD

**Issue by wiegleyj** [johnrengelman/shadow#635] opened 2021-01-29 03:56 UTC
Please check the [User Guide](http://imperceptiblethoughts.com/shadow) before submitting "how do I do 'x'?" questions!

### Shadow Version
6.1.0

### Gradle Version
6.8.1

### Expected Behavior
Build a fat jar file WITHOUT a main class, just a library, but include all the dependencies the library uses.

### Actual Behavior
Either shadow task doesn't run or it complains about missing MainClassName

### Gradle Build Script(s)
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'com.github.jengelman.gradle.plugins:shadow:6.1.0'
    }
}

apply plugin: 'java'
//apply plugin: 'jacoco'
apply plugin: 'maven-publish'
apply plugin: 'com.github.johnrengelman.shadow'

repositories {
    jcenter()
}

dependencies {
    testImplementation 'junit:junit:4.13.1'
    implementation 'org.apache.poi:poi:4.1.2'
    implementation 'org.apache.poi:poi-ooxml:4.1.2'
    implementation 'org.apache.commons:commons-csv:1.8'
}

### Content of Shadow JAR (`jar tf <jar file>` - post link to GIST if too long)

I'm using this in netbeans. When Clean/Build shadow doesn't run. If change
   id 'java'
to
   id 'application'

then shadow runs but it complains "No value has been specified for property 'mainClassName'." because of course... there is no main class because this is all suppose to be a library.

Users of my library can't just magically guess what the dependencies of my library are. I like to supply a library that when they use my methods all the dependencies are in that same jar file and loaded on demand.

How can I get the dependent libraries to be included my jar file?

Oh... warning my brain is stuck back in the 80's with "make" so I'm not too savvy with gradle's awesomeness.

Thank you!

**Comment by johnrengelman** [comment] 2021-02-21 01:37
Duplicate of #609

**Closed by johnrengelman** 2021-02-21 01:37 UTC
