### ISSUE TITLE
The JAR file generated by ShadowJar can be broken when system encoding is not UTF-8

### ISSUE THREAD

**Issue by trustin** [johnrengelman/shadow#283] opened 2017-03-27 09:46 UTC
### Shadow Version

1.2.4

### Gradle Version

3.4.1

### Expected Behavior

When system encoding is not UTF-8 and one of the input file names contain CJK characters, ShadowJar should produce a valid JAR file.

### Actual Behavior

ShadowJar produces a valid ZIP but not a valid JAR because it does not enforce 'UTF-8' encoding when creating a `ZipOutputStream` which defaults to the system's default encoding.

### Gradle Build Script(s)

N/A

### Content of Shadow JAR (`jar tf <jar file>` - post link to GIST if too long)

JAR fails when it encounters the problematic file whose path contains a CJK character because the entry contains a non-UTF string.

### Workaround

```groovy
// Work around the bug where ShadowJar does not set the character set of the output JAR correctly.
class ShadowJar extends com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar {
    @Override
    protected ZipCompressor getInternalCompressor() {
        return new DefaultZipCompressor(false, ZipOutputStream.DEFLATED) {
            @Override
            ZipOutputStream createArchiveOutputStream(File destination) {
                ZipOutputStream zout = super.createArchiveOutputStream(destination)
                zout.setEncoding("UTF-8")
                return zout
            }
        }
    }
}
```

**Comment by trustin** [comment] 2017-03-27 09:48
Proper fix would be to make DefaultZipCompressor to respect the `metadataCharset` property of the `Jar` task.

**Comment by johnrengelman** [comment] 2017-04-29 02:53
Duplicate of https://github.com/johnrengelman/shadow/issues/223

**Closed** 2017-04-29 02:57 UTC
Labels: bug
