### ISSUE TITLE
Build dependency to runtime project dependencies

### ISSUE THREAD

**Issue by levsa** [johnrengelman/shadow#181] opened 2016-02-18 13:14 UTC
I realized that in a project where I'm using the shadow plugin, that has a runtime project dependency to another project, that other project isn't automatically built and the artifact from it is silently left out. Compile dependency works though, the project is built and the artifact is included in the shadowed jar.

**Comment by johnrengelman** [comment] 2016-02-18 17:25
Duplicate of https://github.com/johnrengelman/shadow/issues/152

**Closed by johnrengelman** 2016-02-18 17:25 UTC
