### ISSUE TITLE
No value has been specified for property 'mainClassName'

### ISSUE THREAD

**Issue by filtastisch** [johnrengelman/shadow#628] opened 2021-01-02 08:24 UTC
I'm trying to build an executable Jar with ShadowJar, but everytime it throws the error:
```
A problem was found with the configuration of task ':shadowJar' (type 'ShadowJar').
> No value has been specified for property 'mainClassName'.

```

So, i really dont know what to do.
Here my build.grandle:
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.github.jengelman.gradle.plugins:shadow:2.0.4'
    }
}

plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '2.0.4'
}

mainClassName = "de.filtastisch.discord.beatbot.Main"

group 'de.filtastisch.discord'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    compile 'net.dv8tion:JDA:4.2.0_225'
}
```

**Comment by sergeykad** [comment] 2021-01-10 12:42
Duplicate of https://github.com/johnrengelman/shadow/issues/609

**Closed** 2021-02-21 01:36 UTC
